create table IF NOT EXISTS users (
    user_id int generated by default as identity primary key,
    user_email varchar(50),
    user_login varchar(20),
    user_name varchar(20),
    user_birthday date
);

--alter table USERS
  --  alter column USER_NAME set default user_login;

create table IF NOT EXISTS friends (
    user_id int REFERENCES users(user_id) on delete cascade ,
    friends_id int REFERENCES users(user_id) ON DELETE CASCADE ,
    friends_confirmed varchar(3),
    PRIMARY KEY (user_id, friends_id)
);

CREATE TABLE IF NOT EXISTS rating (
    rating_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    rating_description varchar(10)
);

create table IF NOT EXISTS films (
    film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    film_name VARCHAR(30),
    film_description VARCHAR(300),
    film_duration INT,
    film_date DATE,
    rating_id varchar(10) references RATING(rating_id) on delete set null
);

CREATE TABLE IF NOT EXISTS film_respect_from_user (
    film_id INT REFERENCES films(film_id) ON DELETE CASCADE ,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE ,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    genre_name varchar(30)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id int REFERENCES films(film_id) ON DELETE CASCADE ,
    genre_id int references genre(genre_id) ON DELETE CASCADE ,
    primary key (film_id, genre_id)
);



