create table IF NOT EXISTS users (
    user_id int generated by default as identity primary key,
    user_email varchar(50),
    user_login varchar(20),
    user_name varchar(20),
    user_birthday date
);

create table IF NOT EXISTS friends (
    user_id int REFERENCES users(user_id),
    friends_id int REFERENCES users(user_id),
    friends_confirmed varchar(3),
    PRIMARY KEY (user_id, friends_id)
);

create table IF NOT EXISTS films (
    film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    film_name VARCHAR(30),
    film_description VARCHAR(300),
    film_duration INT,
    film_date DATE,
    film_ratingMPI varchar(10)
);

CREATE TABLE IF NOT EXISTS film_respect_from_user (
    film_id INT REFERENCES films(film_id),
    user_id INT REFERENCES users(user_id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    genre_name varchar(30)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id int REFERENCES films(film_id),
    genre_id int references genre(genre_id),
    primary key (film_id, genre_id)
);

